#!/usr/bin/env bash
# Regenerates certificates.hpp. Needs the openssl and clang-format command line tools.
#
# root                          CA, trusted by the test client
#   intermediate                CA
#     leaf_behind_intermediate  SAN localhost
#   leaf_valid                  SAN localhost
#   leaf_expired                SAN localhost, valid 2020..2021
#   leaf_not_yet_valid          SAN localhost, valid 2100..2110
#   leaf_client_auth_only       SAN localhost, EKU clientAuth
#   leaf_wrong_host             SAN aero-test
# leaf_self_signed              SAN localhost, not signed by root
#
# All leaves share one private key (leaf_key) to keep the header small.

set -e
export MSYS_NO_PATHCONV=1

cd "$(dirname "$0")"
here=$PWD
trap 'rm -rf "$here/tmp"' EXIT
mkdir -p tmp
cd tmp

cat > ca.cnf <<'CNF'
[ca]
default_ca = ca_default

[ca_default]
dir = .
database = $dir/index.txt
new_certs_dir = $dir
serial = $dir/serial
default_md = sha256
policy = policy_any
unique_subject = no
email_in_dn = no

[policy_any]
commonName = supplied

[req]
distinguished_name = req_dn
prompt = no

[req_dn]
CN = placeholder

[ext_ca]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always

[ext_server_localhost]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always

[ext_client_localhost]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
subjectAltName = DNS:localhost
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always

[ext_server_aero_test]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:aero-test
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
CNF

echo 1000 > serial
: > index.txt

FROM=20260101000000Z
UNTIL=21260101000000Z
ca() { openssl ca -batch -notext -config ca.cnf "$@" 2>/dev/null; }

openssl genrsa -out root.key 2048 2>/dev/null
openssl req -new -key root.key -subj /CN=aero-test-root -out root.csr
ca -selfsign -keyfile root.key -in root.csr -out root.crt -extensions ext_ca -startdate $FROM -enddate $UNTIL

openssl genrsa -out intermediate.key 2048 2>/dev/null
openssl req -new -key intermediate.key -subj /CN=aero-test-intermediate -out intermediate.csr
ca -cert root.crt -keyfile root.key -in intermediate.csr -out intermediate.crt -extensions ext_ca -startdate $FROM -enddate $UNTIL

openssl genrsa -out leaf.key 2048 2>/dev/null
openssl req -new -key leaf.key -subj /CN=localhost -out localhost.csr
openssl req -new -key leaf.key -subj /CN=aero-test -out aero-test.csr

ca -cert root.crt -keyfile root.key -in localhost.csr -out leaf_valid.crt -extensions ext_server_localhost -startdate $FROM -enddate $UNTIL
ca -cert root.crt -keyfile root.key -in localhost.csr -out leaf_expired.crt -extensions ext_server_localhost -startdate 20200101000000Z -enddate 20210101000000Z
ca -cert root.crt -keyfile root.key -in localhost.csr -out leaf_not_yet_valid.crt -extensions ext_server_localhost -startdate 21000101000000Z -enddate 21100101000000Z
ca -cert root.crt -keyfile root.key -in localhost.csr -out leaf_client_auth_only.crt -extensions ext_client_localhost -startdate $FROM -enddate $UNTIL
ca -cert root.crt -keyfile root.key -in aero-test.csr -out leaf_wrong_host.crt -extensions ext_server_aero_test -startdate $FROM -enddate $UNTIL
ca -cert intermediate.crt -keyfile intermediate.key -in localhost.csr -out leaf_behind_intermediate.crt -extensions ext_server_localhost -startdate $FROM -enddate $UNTIL
ca -selfsign -keyfile leaf.key -in localhost.csr -out leaf_self_signed.crt -extensions ext_server_localhost -startdate $FROM -enddate $UNTIL

OUT=../certificates.hpp
echo '#pragma once' > $OUT
echo '' >> $OUT
echo '// Generated by generate.sh. Do not edit by hand.' >> $OUT
echo '' >> $OUT
echo '#include <string_view>' >> $OUT
echo '' >> $OUT
echo 'namespace aero::tests::certificates {' >> $OUT
echo '' >> $OUT

for pair in root:root.crt intermediate:intermediate.crt leaf_key:leaf.key \
            leaf_valid:leaf_valid.crt leaf_expired:leaf_expired.crt leaf_not_yet_valid:leaf_not_yet_valid.crt \
            leaf_client_auth_only:leaf_client_auth_only.crt leaf_wrong_host:leaf_wrong_host.crt \
            leaf_behind_intermediate:leaf_behind_intermediate.crt leaf_self_signed:leaf_self_signed.crt
do
  name=${pair%%:*}
  file=${pair#*:}
  echo "  constexpr std::string_view $name =" >> $OUT
  sed 's/.*/    "&\\n"/' $file >> $OUT
  echo '    ;' >> $OUT
  echo '' >> $OUT
done

echo '} // namespace aero::tests::certificates' >> $OUT

cd ..
clang-format -i certificates.hpp
echo "wrote certificates.hpp"
